name: publish dev or beta

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'NPM tag'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - beta
      package:
        description: 'packages'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - config
          - sdk
          - utils
          - transact

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-beta-dev:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ¤˜ checkout
        uses: actions/checkout@v3

      - name: âš™ï¸ Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 18.x
          cache: 'npm'

      - name: ğŸ” Authenticate with NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - run: npm ci --ignore-scripts

      - name: ğŸ› ï¸ Build
        run: npm run build

      - name: ğŸš€ Publish utils
        if: inputs.package == 'all' || inputs.package == 'utils'
        working-directory: ./packages/utils
        run: |
          npm version $(../../scripts/get_next_version.sh xcm-utils ${{ inputs.tag }}) --no-git-tag-version
          npm publish --tag ${{ inputs.tag }}

      - name: ğŸš€ Publish config
        if: inputs.package == 'all' || inputs.package == 'config'
        working-directory: ./packages/config
        run: |
          npm version $(../../scripts/get_next_version.sh xcm-config ${{ inputs.tag }}) --no-git-tag-version
          npm publish --tag ${{ inputs.tag }}

      - name: ğŸš€ Publish sdk
        if: inputs.package == 'all' || inputs.package == 'sdk'
        working-directory: ./packages/sdk
        run: |
          npm version $(../../scripts/get_next_version.sh xcm-sdk ${{ inputs.tag }}) --no-git-tag-version
          npm publish --tag ${{ inputs.tag }}

      - name: ğŸš€ Publish transact
        if: inputs.package == 'all' || inputs.package == 'transact'
        working-directory: ./packages/transact
        run: |
          npm version $(../../scripts/get_next_version.sh xcm-transact ${{ inputs.tag }}) --no-git-tag-version
          npm publish --tag ${{ inputs.tag }}
